---
- name: 'Linux Reboot'
  gather_facts: no
  hosts: "{{ VARIABLE_HOST | default('all') }}"
  tasks:


  - name: 'Slack Message'
    uri:
     url: '{{WEBHOOKS}}'
     method: POST
     body: '{"thread_ts": {{THREAD}},"text":"{{SLACKMESSAGE1}}"}'
     body_format: json
     headers:
      Content-type: "application/json"
    delegate_to: localhost

  - name: 'Shutdown'
    become: yes
    become_method: sudo
    become_user: root
    shell: shutdown now
